### ISSUE TITLE
Cloud storage import loads url instead of text and videos works fine for images

### ISSUE THREAD

**Issue by NavjotBansal** [heartexlabs/label-studio#1221]
**Describe the bug**
While importing text and video format documents from object-storage aws/azure the document is represented in the form of the preauth URL. 

**To Reproduce**
1. Connect your aws container blob and import txt files from it
2. Select a default NER tagging from labeling interface.
3. Sync the data. 
4. Go to tasks
5. Click on any task and verify

**Expected behavior**
Its working fine for images. It should load the video / content of the text. It works perfectly fine for local images but not for object storage. I first thought its CORS problem but it isn't. Still not able to find the root cause.

**Screenshots**
https://drive.google.com/file/d/1w2BedxXJ_3S8rPhpR92b4CGK68oOmCvo/view?usp=sharing

**Environment (please complete the following information):**
 - OS: MacOS
 - Label Studio Version [1.1.0]

**Additional context**
Not able to find the root casue of problem

**Comment by NavjotBansal** [comment]
Hi guys chaning the template for text annotation to 
<View>
  <Labels name="label" toName="text">
    <Label value="PER" background="red"/>
    <Label value="ORG" background="darkorange"/>
    <Label value="LOC" background="orange"/>
    <Label value="MISC" background="green"/>
  </Labels>
  <Text name="text" value="$url" valueType="url"/>
</View>

Worked is there a similar workaround for videos as well?

**Comment by makseq** [comment]
@NavjotBansal Please check the latest master commits, we merged some edits about <Video> tag, it must work as you expected, but without valueType. Just write <Video value="$url" />

**Comment by NavjotBansal** [comment]
@makseq I am able to fix the video issue by changing the
`  <HyperText name="video" value="$video"/>
to 
  <Video name="video" value="$url" valueType="url"/>
`
The latest commit is still not resolving the issue

**Comment by makseq** [comment]
@NavjotBansal For video we finally released <Video> tag, it should solve this problem. 
Please check: https://labelstud.io/tags/video.html
