### ISSUE TITLE
nested choices annotation not saved if the first region in the list does not have a choice containing nested choices

### ISSUE THREAD

**Issue by function2-llx** [heartexlabs/label-studio#1296]
**Describe the bug**
Considering a task that to select several regions from text, select choice for each region and some choice has nested choices below. It is found that the submitted/updated results will not contain the annotation of all nested choices, if the first region in the result list is not selected with a choice containing nested choices. On the other hand, when the first region is selected with a choice containing nested choices, the submitting/updating works properly.

The bug is so difficult to describe and my English is not so good, hope the reproduction and screenshots below would clarify my description.

**To Reproduce**
1. Create a project with the following labeling interface
```xml
<View>
  <View style="display:flex;align-items:start;gap:8px;flex-direction:column">
    <View style="height: 200px; overflow: auto">
      <Text name="text" value="$text"/>
    </View>
    <Labels name="label" toName="text" showInline="true">
      <Label value="label"/>
    </Labels>
    <Choices name="choices" toName="text" showInline="true" choice="multiple" perRegion="true" whenTagName="label">
      <Choice value="choice"/>
      <Choice value="choice(nest)"/>
    </Choices>
    <Choices name="nested-choices" toName="text" showInline="true" choice="multiple" perRegion="true" visibleWhen="choice-selected" whenTagName="choices" whenChoiceValue="choice(nest)">
      <Choice value="nested choice"/>
      <Choice value="another nested choice"/>
    </Choices>
  </View>
</View>
```
2. upload some data, e.g.
```json
{
    "text": "some random text\nanother random text\n"
}
```
3. Click the label, select arbitrary region, and select "choice" from the list of choices
4. Click the label, select arbitrary region, and select "choice(nest)", then select "nested choice" from the emerged list of nested choices.
5. Click "submit", the selection of "nested choice" for the second region is missing after reloading.
6. Repeat the steps above with step 3, 4 swapped, the "nested choice" is kept after submitting.

**Expected behavior**
The nested choices are kept all the time as long as selected despite the order.

**Screenshots**
![nest](https://user-images.githubusercontent.com/38486514/129483479-42ec8426-710a-4c11-9abe-114e436138ff.gif)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 (WSL2)
 - Label Studio Version: 1.1.1

**Additional context**
The (formatted) payload of the request made by the frontend several seconds after selecting "nested choice" in the step 4 above, it can be found that the annotation is already missing here. Maybe the fronend takes the first region for each label as a template?
```json
{
    "lead_time": 18.309,
    "result": [
        {
            "value": {
                "start": 0,
                "end": 16,
                "text": "some random text",
                "labels": [
                    "label"
                ]
            },
            "id": "R_zqTh0Prq",
            "from_name": "label",
            "to_name": "text",
            "type": "labels"
        },
        {
            "value": {
                "start": 0,
                "end": 16,
                "text": "some random text",
                "choices": [
                    "choice"
                ]
            },
            "id": "R_zqTh0Prq",
            "from_name": "choices",
            "to_name": "text",
            "type": "choices"
        },
        {
            "value": {
                "start": 17,
                "end": 36,
                "text": "another random text",
                "labels": [
                    "label"
                ]
            },
            "id": "ytMdW1cnji",
            "from_name": "label",
            "to_name": "text",
            "type": "labels"
        },
        {
            "value": {
                "start": 17,
                "end": 36,
                "text": "another random text",
                "choices": [
                    "choice(nest)"
                ]
            },
            "id": "ytMdW1cnji",
            "from_name": "choices",
            "to_name": "text",
            "type": "choices"
        }
    ],
    "draft_id": 0,
    "project": "4"
}
```

**Comment by hlomzik** [comment]
Hi! This issue was fixed some time ago, it is already in [LSF master](https://github.com/heartexlabs/label-studio-frontend), you can add it to your LabelStudio or you can wait a bit, it will be released soon! Thanks for report, bug is very sad.
To use custom build you can get [artifact from LSF](https://github.com/heartexlabs/label-studio-frontend/actions/runs/1135394369) and add it to LS dir `label_studio/frontend/dist/lsf`

**Comment by function2-llx** [comment]
@hlomzik Thanks for the explanation.

I've replaced files under `label_studio/frontend/dist/lsf` with the latest LSF build, but unfortunately the bug still seems to exist.

And according to [label_studio/frontend/dist/lsf/version.json](https://github.com/heartexlabs/label-studio/blob/7516933600316297384f7704a236a0d7b49d909c/label_studio/frontend/dist/lsf/version.json#L3), currently label-studio is using the frontend built from [this commit in LSF](https://github.com/heartexlabs/label-studio-frontend/commit/6082c430592424ee47f049eec46a26f1bc9e2817), committed on master branch less than a week ago. Could you please check this again?

**Comment by hlomzik** [comment]
Oh, sorry, the problem still exists, right! I fixed similar issue, but about required, not just any nested choice. I see the broken code, so I'll fix it today and notify you!
Thanks for bug report!

**Comment by hlomzik** [comment]
fixed in https://github.com/heartexlabs/label-studio-frontend/commit/34c85b0fcb749bb98d9504c03975e97a398e50ca
you can try the new build

**Comment by function2-llx** [comment]
Ah, happy to confirm that the bug finally gets fixed! Thanks a lot!
