### ISSUE TITLE
Keypoints and bounding boxes change with zoom in-out

### ISSUE THREAD

**Issue by HoseinHashemi** [heartexlabs/label-studio#1691]
**Describe the bug**
Last keypoint jumps once you zoom out, even if you update/submit.
This behavior happens most of the times, but maybe not all the times. The KP jumps to the bottom-right first and once you zoom out again (after correcting it) it then jumps to the top-left. The 3rd time it works.  
Similar thing also happens to bounding boxes. So if you zoom in to fine-tune bounding box edge sometimes the other edges will be fitted to the current zoomed in part. 

**To Reproduce**
1. Do multiple keypoints.
2. Zoom in and pin the last keypoint.
3. Zoom out and you see how the last KP will jump diagonally to the bottom right.
4.  Correct the KP and zoom out for the second time, the KP jumps to the top-left.
5. Correct it and zoom out for the 3rd time and it works.

**Expected behavior**
A consistent position of KPs and BBs regardless of zoom level.

**Screenshots**
Please see below screenshots.
![Screenshot 2021-11-02 114000](https://user-images.githubusercontent.com/33822932/139783696-2d4eae8c-e11c-4926-ac28-c40f344ce444.png)
![Screenshot 2021-11-02 114021](https://user-images.githubusercontent.com/33822932/139783701-5ae3728f-094d-4594-8693-8f94574d3158.png)
![Screenshot 2021-11-02 114158](https://user-images.githubusercontent.com/33822932/139783706-58fd6b20-8b99-4f26-8d1f-073c79272697.png)
![Screenshot 2021-11-02 114214](https://user-images.githubusercontent.com/33822932/139783707-970bd494-3ad9-4d0c-9788-2f8001d6f491.png)

**Environment:**
 - Ubuntu 20.04.2
 - Label Studio Version 1.3

**Comment by makseq** [comment]
@HoseinHashemi We've tried to reproduce this issue, but without success. Could you please record a video?

**Comment by HoseinHashemi** [comment]
Attached is a sample when the bounding box gets changes according to the zoom level. 


https://user-images.githubusercontent.com/33822932/141944646-9b9ca590-4505-4615-8e85-459eeeab06a8.mov

**Comment by niklub** [comment]
https://github.com/heartexlabs/label-studio-frontend/pull/351

**Comment by makseq** [comment]
Relative: https://github.com/heartexlabs/label-studio/issues/1672

**Comment by makseq** [comment]
This problem was fixed in the latest master and heartexlabs/label-studio-frontend#351.

**Comment by ArielShokrany** [comment]
Im using label studio 1.6.0 and im having the same problem.

**Comment by yellowjs0304** [comment]
This bug still exists...
I met this bug randomly.
The polygon coordinate is changed when I use zoom in, zoom out (also using zoom to fit)
Redpoint : original point / white point: changed point
![image](https://github.com/heartexlabs/label-studio/assets/30281608/c321d3b0-c2ce-4af3-89ee-629021304782)

The coordinate difference is really big.
(original point: red / changed point: white)
![image](https://github.com/heartexlabs/label-studio/assets/30281608/668db45e-892f-4b24-9eb7-b72f0c2d4ad4)

p.s. The image and json data were captured in different time. i met this cases several time.
I think this need to fix. @makseq

**Comment by emoebel** [comment]
hi, I am having this issue on macOS 14.3.1 with label studio 1.17.  When zooming in and out, the size of some bounding boxes change. This seems to happen randomly. Very annoying as I have to annotate hundreds of images
