### ISSUE TITLE
AttributeError when trying to run label-studio after installing it via pip

### ISSUE THREAD

**Issue by LightDashing** [heartexlabs/label-studio#2979]
**Describe the bug**
Installed Label Studio via `pip`, as described on main page. However, when I try to run it a Python exception is being thrown:
```
Traceback (most recent call last):
  File "C:\Users\some.user\Miniconda3\envs\label-studio\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,Starting new HTTPS connection (1): o227124.ingest.sentry.io:443

  File "C:\Users\some.user\Miniconda3\envs\label-studio\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\some.user\Miniconda3\envs\label-studio\Scripts\label-studio.exe\__main__.py", line 7, in <module>
  File "C:\Users\some.user\Miniconda3\envs\label-studio\lib\site-packages\label_studio\server.py", line 282, in main
    _setup_env()
  File "C:\Users\some_user\Miniconda3\envs\label-studio\lib\site-packages\label_studio\server.py", line 40, in _setup_env
    application = get_wsgi_application()
  File "C:\Users\some.user\Miniconda3\envs\label-studio\lib\site-packages\django\core\wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "C:\Users\some.user\Miniconda3\envs\label-studio\lib\site-packages\django\__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "C:\Users\some.user\Miniconda3\envs\label-studio\lib\site-packages\django\conf\__init__.py", line 82, in __getattr__
    self._setup(name)
  File "C:\Users\some.user\Miniconda3\envs\label-studio\lib\site-packages\django\conf\__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\some.user\Miniconda3\envs\label-studio\lib\site-packages\django\conf\__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\some.user\Miniconda3\envs\label-studio\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\some.user\Miniconda3\envs\label-studio\lib\site-packages\label_studio\core\settings\label_studio.py", line 46, in <module>
    from label_studio.core.utils.common import collect_versions
  File "C:\Users\some.user\Miniconda3\envs\label-studio\lib\site-packages\label_studio\core\utils\common.py", line 36, in <module>
    from drf_yasg.inspectors import CoreAPICompatInspector, NotHandled
  File "C:\Users\some.user\Miniconda3\envs\label-studio\lib\site-packages\drf_yasg\inspectors\__init__.py", line 5, in <module>
    from .field import (
  File "C:\Users\some.user\Miniconda3\envs\label-studio\lib\site-packages\drf_yasg\inspectors\field.py", line 406, in <module>
    (serializers.NullBooleanField, (openapi.TYPE_BOOLEAN, None)),
AttributeError: module 'rest_framework.serializers' has no attribute 'NullBooleanField'. Did you mean: 'BooleanField'?
```

Tried installing in two separate environments, using python's default venv and using conda, both times same error occured.

**To Reproduce:**

1. run `pip install label-studio`
2. run `label-studio`

**Environment (please complete the following information):**
 - OS: Microsoft Windows 10
 - Label Studio Version: latest version from PyPi

**Comment by nazebzurati** [comment]
It seems that [drf_yasg](https://github.com/axnsan12/drf-yasg) package caused the error (reported [here](https://github.com/axnsan12/drf-yasg/issues/810)).

To temporarily fix the issue, ...
1. Go to your 'drf_yasg' package in your environment. In your case based on the error message, `C:\Users\some.user\Miniconda3\envs\label-studio\lib\site-packages\drf_yasg`.
3. Open `.\inspectors\field.py` file and replace all 'NullBooleanField' to 'BooleanField'.
4. Restart label-studio by running the command `label-studio`.

This is only the workaround if you have urgent work to do. Use with care.

**Comment by scfrank** [comment]
I had the same problem with djangorestframework v. 3.14.0 

`pip install djangorestframework=3.13.1` made the problem go away; label-studio seems to work as intended.

See also: 
https://stackoverflow.com/questions/73823743/attributeerror-module-rest-framework-serializers-has-no-attribute-nullboolea?noredirect=1&lq=1

**Comment by jerzyorlowskimim** [comment]
I have the same problem. Linux Mint 20.2 Uma python3.9

**Comment by makseq** [comment]
It was fixed in this PR
https://github.com/heartexlabs/label-studio/pull/2980/files

**Comment by jerzyorlowskimim** [comment]
HI guys ` pip install -U label-studio` does not improve anything. 
As a good practice, to mark the problem as solved, it is not enough to fix the problem in the source code, You have to release the version with fixes.

**Comment by makseq** [comment]
@jerzyorlowskimim Now it should be fixed in the new release 1.6.

**Comment by Ghriann** [comment]
Problem still here with fresh install in fresh environment, and Anaconda Python.

```
Current platform is win32, apply sqlite fix
Can't load sqlite3.dll from current directory
(...)
```

I tried the fix above and placed the .dll file manually in my current directory (C:\Users\Ghriann), and now the error is :

```
Current platform is win32, apply sqlite fix
Add current directory to PATH for DLL search: C:\Users\Ghriann
(...) (same as above)
```

I added the folder to PATH but the error doesn't change ... I tried everything else above without luck.
Any suggestions ?

**Comment by makseq** [comment]
Try to use Anaconda python, it already has the correct sqlite build.

**Comment by Ghriann** [comment]
Ehm I'm already using Anaconda Python, as stated above.

**Comment by makseq** [comment]
Could you show commands you run from the beginning? Seems like you have some mess in your python environment.

**Comment by jelalsultanov** [comment]
> pip install djangorestframework=3.13.1

yes this also worked for me.

**Comment by vvaradarajan** [comment]
Thx: pip install djangorestframework=3.13.1 - worked
Started happening 'suddenly' - when everything was working fine.  I guess installation of some other package messed this up.

**Comment by jelalsultanov** [comment]
> Thx: pip install djangorestframework=3.13.1 - worked Started happening 'suddenly' - when everything was working fine. I guess installation of some other package messed this up.

same for me

**Comment by makseq** [comment]
it's weird, djangorestframework==3.13.1 is fixed in our requirements.txt. Are you using python virtual environment for LS?

**Comment by vvaradarajan** [comment]
Yes. Python 3.10 or above

**Comment by makseq** [comment]
@vvaradarajan 
Could you try this:
```
pip install -U drf_yasg
pip install -U djangorestframework
```

Will it help?

**Comment by khadijakhaldi** [comment]
please do we need to install SQLite database before installing label studio ?
