### ISSUE TITLE
s3 image url not resolved when used inside Repeater tag

### ISSUE THREAD

**Issue by deoxyribose** [heartexlabs/label-studio#3854]
Hello, I'm trying to import tasks from an s3 bucket, for multi-page document annotation.
I can successfully import a task from the same bucket, when the label config is regular image classification, i.e. 

```     
<View>
     <Image name="image_object" value="$image_url"/>
     <Choices name="image_classes" toName="image_object">
         <Choice value="Cat"/>
         <Choice value="Dog"/>
     </Choices>
 </View>
```

and the task is imported (using the label_studio_sdk python package) with

`project.import_tasks([{"image_url": "s3://bucket-name/example.png"}])`

Then I can see in the app that the task gets resolved as

```
{
  "id": 78676,
  "data": {
    "image_url": "https://bucket-name.s3.amazonaws.com/example.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=madeupcredentialsX-Amz-Date=20230316T094352Z&X-Amz-Expires=60&X-Amz-SignedHeaders=host&X-Amz-Signature=madeupsignature"
  },
  "annotations": [],
  "predictions": []
}
```

However, when I try the same with a multi-page document config:

```
 <View>
    <Repeater on="$document" indexFlag="{{idx}}" mode="pagination">
        <Image name="page_{{idx}}" value="$document[{{idx}}].page" valueType="url" inline="true"/>
        <RectangleLabels name="labels_{{idx}}" toName="page_{{idx}}">
            <Label value="Title" background="green"/>
            <Label value="Date" background="blue"/>
            <Label value="Author" background="yellow"/>
            <Label value="Organization" background="orange"/>
            <Label value="Amount" background="red"/>
        </RectangleLabels>
        <View style="display: flex; justify-content: center;">
            <Header value="Rate this page:"/>
            <Rating name="rating_{{idx}}" toName="page_{{idx}}"/>
        </View>
    </Repeater>
    </View>
```

(tried with and without valueType="url" inside Image tag)

where the task is imported using

```
project.import_tasks(
[
{'document': [{'page': 's3:[//bucket-name/labelstudio1/example1.png'},
               {'page': 's3:[//bucket-name/labelstudio1/example2.png'}]},
 {'document': [{'page': 's3:[//bucket-name/labelstudio2/example3.png'},
               {'page': 's3:[//bucket-name/labelstudio2/example4.png'}]}
]
)
```

the images aren't shown:

```
There was an issue loading URL from $document[0].page value

Things to look out for:

    URL is valid
    URL scheme matches the service scheme, i.e. https and https
    The static server has wide-open CORS, [more on that here](https://labelstud.io/guide/storage.html#Troubleshoot-CORS-and-access-problems)

Technical description:
URL:s3://bucket-name/labelstudio1/example1.png
```

 and looking at the source for the tasks, I get:
```
{
  "id": 78679,
  "data": {
    "document": [
      {
        "page": "s3://bucket-name/labelstudio1/example1.png"
      },
      {
        "page": "s3://bucket-name/labelstudio1/example2.png"
      }
    ]
  },
  "annotations": [],
  "predictions": []
}
```

So for some reason the s3 url doesn't get resolved as a https url, with the credentials etc. appended.
All the settings for the source storage are the same in the two examples, and changing them doesn't break the first example or fix the second: I have Treat every bucket object as a source file and Use pre-signed URL turned on, and no File Filter Regex.

**Comment by AhmedMasry-Arteria** [comment]
Hey!
Has anyone been able to fix this? I am facing the exact same issue and it's blocking me. 
Thanks!

**Comment by makseq** [comment]
Please upgrade to the latest LS version from the github develop branch, this issue was solved there one-two weeks ago.

**Comment by muthurajr** [comment]
@makseq I'm using 1.7.3 but still the uri is not resolved. Do we need to enable any feature flag for this?

**Comment by DoctorSlimm** [comment]
bump using hf spaces deployment and intermittent seeminlgly random cors issues
