### ISSUE TITLE
"error: subprocess-exited-with-error" when installing on Ubuntu

### ISSUE THREAD

**Issue by jmurel** [heartexlabs/label-studio#3910]
**Describe the bug**
I'm unable to install label-studio on my computer.

**To Reproduce**

```
python3 -m venv env
source env/bin/activate
sudo apt install python3.9-dev
python -m pip install label-studio
```

_N.b. I've pasted the documentation's steps for installing on Ubuntu, but the issue reported here comes when also installing via pip and Git_

**Expected behavior**
successful installation of Label Studio

**Screenshots**
[Successful installation of various pkgs followed by:]
```
Collecting psycopg2==2.9.5
  Using cached psycopg2-2.9.5.tar.gz (384 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      /home/jmurel/anaconda3/lib/python3.9/site-packages/setuptools/config/setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running egg_info
      creating /tmp/pip-pip-egg-info-1n0ya7sw/psycopg2.egg-info
      writing /tmp/pip-pip-egg-info-1n0ya7sw/psycopg2.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-1n0ya7sw/psycopg2.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-pip-egg-info-1n0ya7sw/psycopg2.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-1n0ya7sw/psycopg2.egg-info/SOURCES.txt'
      
      Error: pg_config executable not found.
      
      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
      
          python setup.py build_ext --pg-config /path/to/pg_config build ...
      
      or with the pg_config option in 'setup.cfg'.
      
      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.
      
      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Environment (please complete the following information):**

OS: Ubuntu 22.04
Label Studio Version : label_studio-1.7.2-py3-none-any.whl
Conda : 23.1
Kernel : 5.19.0-35-generic

**Additional information for context:**
As mentioned, I've tried the documentation's directions for installing on Ubuntu, as well as via pip and Git, and the above error arises for all three. I have tried installing the PyPI 'psycopg2-binary' pkg as the error direct, but still the issue arises. Any help is appreciated!

**Comment by makseq** [comment]
You mentioned Conda, but I don't see conda command there. Also could you please check your python version, just run python and send first lines here:
```
python
```

**Comment by lboullo0** [comment]
Same error

```
python
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by jmurel** [comment]
@makseq Here is the output of "python" per your request:
```
Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by cozeybozey** [comment]
I have the same error on Debian

Edit:
Fixed it by doing: 

```
conda install psycopg2
```

**Comment by makseq** [comment]
This issue will be fixed in LS 1.7.3 soon.

**Comment by kopyl** [comment]
Same issue. How to install it?

`install psycopg2` did not fix it :(

**Comment by makseq** [comment]
@kopyl 
```
sudo apt-get update
sudo apt-get install libpq-dev python-dev
sudo pip install psycopg2
```

**Comment by kopyl** [comment]
@makseq installing from git (pip install git+...) helped, thanks :)
