### ISSUE TITLE
String not being exported correctly to csv format after upgrading to 1.7.0

### ISSUE THREAD

**Issue by bdeng3** [heartexlabs/label-studio#4033]
**Describe the bug**
Our input data had a string column that might contain commas within the string. When we exported the annotation to csv format, those commas were treated as delimiters. This resulted in many more columns than expected. We solved this problem by downgrading to 1.6.0.

**To Reproduce**
1. Include some texts which has comma in it, import them into label studio
2. Export them into csv format.

**Expected behavior**
We expect the full string to should be exported to the same column. 

**Screenshots**
The improper csv file that being exported: 
![image](https://user-images.githubusercontent.com/89899604/231990403-49a913e2-60e8-4095-97b4-3e48d2ba6024.png)

What the original string looks like:
<img width="936" alt="image" src="https://user-images.githubusercontent.com/89899604/231990825-9901915d-a852-4552-87cc-10f0cfc8639c.png">

**Environment (please complete the following information):**
 - OS: Both MacOS and Windows
 - Label Studio Version 1.7.0 and 1.7.1

**Additional context**

**Comment by makseq** [comment]
This bug was fixed in the latest commits of develop branch and in the latest version (0.0.53) of label-studio-converter.

**Comment by bdeng3** [comment]
Great, thanks for looking into the issue! @makseq but we just upgrade label-studio to 1.7.3, and it seems the problem persists. Is there any way we could install the dev version of label-studio?

**Comment by makseq** [comment]
You can try quick start from the main LS docs page:

```
# Clone repo
git clone https://github.com/heartexlabs/label-studio.git
# Install dependencies
cd label-studio
pip install -e .
# Apply DB migrations
python label_studio/manage.py migrate
# Collect static files
python label_studio/manage.py collectstatic
# Launch
python label_studio/manage.py runserver
```

It's very important to have label-studio-converter > 0.0.53. You can check its version on `/version` page.
