### ISSUE TITLE
Exported project data contains less samples than labelled tasks and 'remove duplicated tasks' does not work with case sensitive filepaths

### ISSUE THREAD

**Issue by massimodt** [heartexlabs/label-studio#5829]
**Describe the bug**
Using local storage and after exporting a project using YOLO format I noticed that some labels were missing, so after some checks I found out that the missing tasks were those having same data field (side note: in my case they have different case). The 'remove duplicated tasks' functionality didn't work.

**To Reproduce**
1. create new project
2. import labels from json file
3. rename local storage folder containing referenced data with different case (e.g. .\Images-> .\images)
4. sync local storage containing referenced data
5. all tasks should display all images (even if filepaths between data and filesystem have different case)
6. every task has one duplicated task
8. using 'remove duplicated tasks' won't work

**Expected behavior**
Since filepaths are treated case-sensitively when removing duplicated tasks I would expect that importing labelled tasks from json file and synching local storage would treat filepaths case-sensitively too.

**Screenshots**
/data/local-files/?d=images\images\Image.png
![image](https://github.com/HumanSignal/label-studio/assets/97591201/ae76a295-ed01-4080-8b3c-92bc1961c219)

/data/local-files/?d=images\Images\Image.png
![image](https://github.com/HumanSignal/label-studio/assets/97591201/77678806-302f-4cc3-bddd-9125cb04e20c)

**Environment (please complete the following information):**
 - OS: Windows
 - Label Studio Version 1.12.0

**Additional context**
Considering that I'm using Windows with case-insensitive file system, it could be for this reason that the images are displayed correctly even for those tasks' data with case-insensitive filepaths. Unix-like operating systems treat filepaths case-sensitively I suppose that it will fail to display those images (I didn't test it).

**Comment by makseq** [comment]
Why do you need this step? 

> 3. rename local storage folder containing referenced data with different case (e.g. .\Images-> .\images)

What paths do you have in your original json file? Images or images? 

Remove duplicates will work only if your task.data will be absolutely the same with other tasks. It sounds like you need to fix paths in your database, you can try running label studio this way: `EXPERIMENTAL_FEATURES=1 label-studio` and try to use `Add or Modify Field` in the data manager actions. There you can type something like `replace("image", "Image")` and it should rename your paths. Then you will be able to run remove duplicates.

**Comment by massimodt** [comment]
In my case step 3 was unintentional, after labelling some images I had to split them into two projects, so I moved all images into two folders and renamed them, I also splitted the json array and renamed the task.data, unfortunately I missed a lower case letter. After importing the labels, all seemed fine until I found out that there were duplicated tasks and I was labelling images twice. In my user experience it would have helped me save some time if the front end didn't display the images having a 'wrong' case filepath.

Thank you, I didn't know about this feature to modify fields, I managed to fix filepaths in the json file directly and after reimporting it it worked fine.

As a newbie I spent some time to figure it out so I thought that if this happens to someone else this issue might be helpful.

**Comment by makseq** [comment]
Also you could filter your tasks by path using Data manager filters and remove all images that you don't need.

**Comment by massimodt** [comment]
oh nice, I can filter by 'Storage filename', that is helpful too!

**Comment by makseq** [comment]
Is this issue solved now?

**Comment by massimodt** [comment]
I think it's still an issue, images should be displayed case-sensitively, it shouldn't happen to have duplicated tasks and 'remove duplicated tasks' does not remove them. Do you agree?

Would it be helpful a pull request to display images case-sensitively?

**Comment by massimodt** [comment]
in my opinion 'duplicated task' means that it points to the same data source, I think this is the case.

**Comment by massimodt** [comment]
unfortunately I don't have enough time to contribute to this project, I will close this issue. If anyone else finds useful to fix it feel free to reopen. Thanks @makseq!
