### ISSUE TITLE
A bug with CSRF  after update label-studio

### ISSUE THREAD

**Issue by lgq-garbage** [heartexlabs/label-studio#6296]
![17253509171808](https://github.com/user-attachments/assets/3351cb23-7767-47b9-b600-c7bece2fcf3d)

I update label-studio to the newest version and run  docker-compose up -d --build.    

But when I open the 8080 port, the website shows these.(Include edge or chrome

**Comment by lgq-garbage** [comment]
This problem appears again. Anyone meets this problem？  I don’t know how to adjust files.

**Comment by june-oh** [comment]
Same problem

**Comment by june-oh** [comment]
I found a temporary workaround. Add `USE_ENFORCE_CSRF_CHECKS=false` to the `docker-compose.yml` file as shown below:
```
app:  
   stdin_open: true  
   tty: true  
   build: .  
   image: heartexlabs/label-studio:latest  
   restart: unless-stopped  
   expose:  
     - "8000"  
   depends_on:  
     - db  
   environment:  
     - DJANGO_DB=default  
     - POSTGRE_NAME=postgres  
     - POSTGRE_USER=postgres  
     - POSTGRE_PASSWORD=  
     - POSTGRE_PORT=5432  
     - POSTGRE_HOST=db  
     - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}  
     - JSON_LOG=1  
     - USE_ENFORCE_CSRF_CHECKS=false     #add this line 
```

**Comment by lgq-garbage** [comment]
Thanks，I&nbsp; will&nbsp; add&nbsp; this option&nbsp; and rebuild.



---Original---
From: ***@***.***&gt;
Date: Wed, Sep 4, 2024 18:42 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [HumanSignal/label-studio] A bug with CSRF  after updatelabel-studio (Issue #6296)




 
I found a temporary workaround. Add USE_ENFORCE_CSRF_CHECKS=false to the docker-compose.yml file as shown below:
 app:      stdin_open: true      tty: true      build: .      image: heartexlabs/label-studio:latest      restart: unless-stopped      expose:        - "8000"      depends_on:        - db      environment:        - DJANGO_DB=default        - POSTGRE_NAME=postgres        - POSTGRE_USER=postgres        - POSTGRE_PASSWORD=        - POSTGRE_PORT=5432        - POSTGRE_HOST=db        - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}        - JSON_LOG=1        - USE_ENFORCE_CSRF_CHECKS=false     #add this line

**Comment by june-oh** [comment]
@lgq-garbage  Actually, I tried it out, and it seems like this change works with just `docker compose up` without needing to run `docker compose --rebuild`

**Comment by jombooth** [comment]
/jira create
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/10708389097)
> Jira issue [TRIAG-822](https://humansignal.atlassian.net/browse/TRIAG-822) is created

[TRIAG-822]: https://humansignal.atlassian.net/browse/TRIAG-822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jombooth** [comment]
Disabling CSRF as shown above will fix this, but note that it also makes Label Studio less secure. I've also seen this bug a few times on my own setup, and will flag it for the engineering team.

**Comment by jombooth** [comment]
Note also that a hard refresh (ctrl+shift+R / cmd+shift+R in chrome) can help resolve this issue when it comes up.

**Comment by lgq-garbage** [comment]
Great.

**Comment by gawbul** [comment]
> Disabling CSRF as shown above will fix this, but note that it also makes Label Studio less secure. I've also seen this bug a few times on my own setup, and will flag it for the engineering team.

I was just about to post the very same. This is a security risk for us, and although it works in the interim, it's not the ideal solution in the long run. It would be great to get a longer term fix on this, an issue which just spontaneously impacted us this week. Is there any estimate on the time for a fix on this? I'm assuming it is still an issue in 1.13.1 (we're still on 1.12.1)? @jombooth

**Comment by jombooth** [comment]
Hi @gawbul and others - I fixed this in #6344. There shouldn't be any need to disable CSRF anymore once you pull latest `develop` and rebuild.

**Comment by TheAIWizard** [comment]
Hi,

I'm still encountering the 403 Forbidden error related to CSRF, mentioned here in https://github.com/HumanSignal/label-studio/issues/6296, even after updating to version 1.14.0, which was supposed to address the CSRF errors when using Docker (https://github.com/HumanSignal/label-studio/pull/6344).

Could you please assist with resolving this?

Thanks in advance!
