### ISSUE TITLE
Audio playing pointer doesn't move to the position of mouse

### ISSUE THREAD

**Issue by SN4KEBYTE** [heartexlabs/label-studio#825]
**Describe the bug**
In the audio task, when I click the audio waveform, the audio playing pointer does not move to the position of my mouse pointer, resulting in that every time I want to listen to a part in the middle, I always listen from the beginning.

![Label Studio Bug](https://user-images.githubusercontent.com/36272321/115355355-ca163300-a1e4-11eb-86a6-d9479ef59632.gif)

**To Reproduce**
1. Go to 'labeling'
2. Click on waveform
3. See error that the audio playing pointer does not move to the position of my mouse pointer

**Expected behavior**
The audio playing pointer move to the position of my mouse pointer.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Label Studio Version: 1.0.0

**Additional context**
This problem does not exist in the ’interface preview‘ in the ‘Setup’, but it will appear when labeling.

This issue was also mentioned here: https://github.com/heartexlabs/label-studio/issues/306

**Comment by makseq** [comment]
Please, try the latest commits from master branch. I hope it's fixed there.

**Comment by SN4KEBYTE** [comment]
Thank you for response, I'll try it!

**Comment by SN4KEBYTE** [comment]
I've tried the latest commits, but the bug is still active :(

**Comment by makseq** [comment]
@SN4KEBYTE Could you send your http://localhost:8080/version page? (or `label-studio version`)

**Comment by SN4KEBYTE** [comment]
@makseq 
{
  "package": {
    "version": "1.0.1",
    "short_version": "1.0",
    "latest_version_from_pypi": "1.0.1",
    "latest_version_upload_time": "2021-04-05T19:13:41",
    "current_version_is_outdated": false
  },
  "backend": {
    "commit": "71278b",
    "date": "2021-04-05 11:30:54 -0700",
    "branch": "master",
    "version": "1.0.0+87.g71278b0b"
  },
  "label-studio-frontend": {
    "commit": "5164462ced2fe8a0bbdd7cd9c4a5bec3772577ab",
    "branch": "master",
    "date": "2021-03-31T10:57:00Z"
  },
  "dm2": {
    "commit": "7751a996682f145d651123af27286f4f392c293c",
    "branch": "master",
    "date": "2021-04-02T13:15:22Z"
  }
}

**Comment by makseq** [comment]
I see you are using LS backend from 05 April, but we fixed it about 14 days ago: https://github.com/heartexlabs/label-studio/pull/806

I recommend you to use master branch to solve this trouble.

**Comment by SN4KEBYTE** [comment]
I've tried this version, but this bug is still here

{
  "package": {
    "version": "1.0.1",
    "short_version": "1.0",
    "latest_version_from_pypi": "1.0.1",
    "latest_version_upload_time": "2021-04-05T19:13:41",
    "current_version_is_outdated": false
  },
  "backend": {
    "commit": "0984e0",
    "date": "2021-04-23 22:52:56 +0000",
    "branch": "master",
    "version": "1.0.1+41.g0984e0f"
  },
  "label-studio-frontend": {
    "commit": "5164462ced2fe8a0bbdd7cd9c4a5bec3772577ab",
    "branch": "master",
    "date": "2021-03-31T10:57:00Z"
  },
  "dm2": {
    "commit": "7751a996682f145d651123af27286f4f392c293c",
    "branch": "master",
    "date": "2021-04-02T13:15:22Z"
  }
}

**Comment by SN4KEBYTE** [comment]
Thank you, this problem was solved!
I've tested it on WSL2 Ubuntu 20.04, but on Windows 10 I had an error while creating project.

**Comment by makseq** [comment]
@SN4KEBYTE What problem did you have on Windows?

**Comment by Morgana025** [comment]
Hi, I'm getting the same error :( 
My environment is:

- OS: Windows 10
- Browser: chrome
- Version: 1.2

I tried to downgrade to version 1.1.0 but the issue is still there. Do you have any suggestions?
Thanks

**Comment by makseq** [comment]
@Morgana025 Coud you record a video?
